version: '3'

services:
  node:
    container_name: node_1
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: db_1
    image: mongo
    ports:
      - '27017:27107'
